// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBus.Data;

#nullable disable

namespace TicketBus.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250520081027_updateDB")]
    partial class updateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TicketBus.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TicketBus.Models.Bill", b =>
                {
                    b.Property<int>("IdBill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBill"));

                    b.Property<string>("BillCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinalTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdPassenger")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeatQuantity")
                        .HasColumnType("int");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.HasKey("IdBill");

                    b.HasIndex("IdPassenger");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("TicketBus.Models.Brand", b =>
                {
                    b.Property<int>("IdBrand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBrand"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegistFormId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdBrand");

                    b.HasIndex("UserId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("TicketBus.Models.BusRoute", b =>
                {
                    b.Property<int>("IdRoute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoute"));

                    b.Property<int?>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("IdBrand")
                        .HasColumnType("int");

                    b.Property<int?>("IdEndCity")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegist")
                        .HasColumnType("int");

                    b.Property<int?>("IdStartCity")
                        .HasColumnType("int");

                    b.Property<string>("NameRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TravelTime")
                        .HasColumnType("time");

                    b.HasKey("IdRoute");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdEndCity");

                    b.HasIndex("IdRegist");

                    b.HasIndex("IdStartCity");

                    b.ToTable("BusRoutes");
                });

            modelBuilder.Entity("TicketBus.Models.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCity"));

                    b.Property<string>("CityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCity");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            IdCity = 1,
                            CityCode = "TP01",
                            NameCity = "Hà Nội"
                        },
                        new
                        {
                            IdCity = 2,
                            CityCode = "TP02",
                            NameCity = "Hồ Chí Minh"
                        },
                        new
                        {
                            IdCity = 3,
                            CityCode = "TP03",
                            NameCity = "Hải Phòng"
                        },
                        new
                        {
                            IdCity = 4,
                            CityCode = "TP04",
                            NameCity = "Đà Nẵng"
                        },
                        new
                        {
                            IdCity = 5,
                            CityCode = "TP05",
                            NameCity = "Cần Thơ"
                        },
                        new
                        {
                            IdCity = 6,
                            CityCode = "TP06",
                            NameCity = "An Giang"
                        },
                        new
                        {
                            IdCity = 7,
                            CityCode = "TP07",
                            NameCity = "Bà Rịa - Vũng Tàu"
                        },
                        new
                        {
                            IdCity = 8,
                            CityCode = "TP08",
                            NameCity = "Bắc Giang"
                        },
                        new
                        {
                            IdCity = 9,
                            CityCode = "TP09",
                            NameCity = "Bắc Kạn"
                        },
                        new
                        {
                            IdCity = 10,
                            CityCode = "TP10",
                            NameCity = "Bạc Liêu"
                        },
                        new
                        {
                            IdCity = 11,
                            CityCode = "TP11",
                            NameCity = "Bắc Ninh"
                        },
                        new
                        {
                            IdCity = 12,
                            CityCode = "TP12",
                            NameCity = "Bến Tre"
                        },
                        new
                        {
                            IdCity = 13,
                            CityCode = "TP13",
                            NameCity = "Bình Định"
                        },
                        new
                        {
                            IdCity = 14,
                            CityCode = "TP14",
                            NameCity = "Bình Dương"
                        },
                        new
                        {
                            IdCity = 15,
                            CityCode = "TP15",
                            NameCity = "Bình Phước"
                        },
                        new
                        {
                            IdCity = 16,
                            CityCode = "TP16",
                            NameCity = "Bình Thuận"
                        },
                        new
                        {
                            IdCity = 17,
                            CityCode = "TP17",
                            NameCity = "Cà Mau"
                        },
                        new
                        {
                            IdCity = 18,
                            CityCode = "TP18",
                            NameCity = "Cao Bằng"
                        },
                        new
                        {
                            IdCity = 19,
                            CityCode = "TP19",
                            NameCity = "Đắk Lắk"
                        },
                        new
                        {
                            IdCity = 20,
                            CityCode = "TP20",
                            NameCity = "Đắk Nông"
                        },
                        new
                        {
                            IdCity = 21,
                            CityCode = "TP21",
                            NameCity = "Điện Biên"
                        },
                        new
                        {
                            IdCity = 22,
                            CityCode = "TP22",
                            NameCity = "Đồng Nai"
                        },
                        new
                        {
                            IdCity = 23,
                            CityCode = "TP23",
                            NameCity = "Đồng Tháp"
                        },
                        new
                        {
                            IdCity = 24,
                            CityCode = "TP24",
                            NameCity = "Gia Lai"
                        },
                        new
                        {
                            IdCity = 25,
                            CityCode = "TP25",
                            NameCity = "Hà Giang"
                        },
                        new
                        {
                            IdCity = 26,
                            CityCode = "TP26",
                            NameCity = "Hà Nam"
                        },
                        new
                        {
                            IdCity = 27,
                            CityCode = "TP27",
                            NameCity = "Hà Tĩnh"
                        },
                        new
                        {
                            IdCity = 28,
                            CityCode = "TP28",
                            NameCity = "Hải Dương"
                        },
                        new
                        {
                            IdCity = 29,
                            CityCode = "TP29",
                            NameCity = "Hậu Giang"
                        },
                        new
                        {
                            IdCity = 30,
                            CityCode = "TP30",
                            NameCity = "Hòa Bình"
                        },
                        new
                        {
                            IdCity = 31,
                            CityCode = "TP31",
                            NameCity = "Hưng Yên"
                        },
                        new
                        {
                            IdCity = 32,
                            CityCode = "TP32",
                            NameCity = "Khánh Hòa"
                        },
                        new
                        {
                            IdCity = 33,
                            CityCode = "TP33",
                            NameCity = "Kiên Giang"
                        },
                        new
                        {
                            IdCity = 34,
                            CityCode = "TP34",
                            NameCity = "Kon Tum"
                        },
                        new
                        {
                            IdCity = 35,
                            CityCode = "TP35",
                            NameCity = "Lai Châu"
                        },
                        new
                        {
                            IdCity = 36,
                            CityCode = "TP36",
                            NameCity = "Lâm Đồng"
                        },
                        new
                        {
                            IdCity = 37,
                            CityCode = "TP37",
                            NameCity = "Lạng Sơn"
                        },
                        new
                        {
                            IdCity = 38,
                            CityCode = "TP38",
                            NameCity = "Lào Cai"
                        },
                        new
                        {
                            IdCity = 39,
                            CityCode = "TP39",
                            NameCity = "Long An"
                        },
                        new
                        {
                            IdCity = 40,
                            CityCode = "TP40",
                            NameCity = "Nam Định"
                        },
                        new
                        {
                            IdCity = 41,
                            CityCode = "TP41",
                            NameCity = "Nghệ An"
                        },
                        new
                        {
                            IdCity = 42,
                            CityCode = "TP42",
                            NameCity = "Ninh Bình"
                        },
                        new
                        {
                            IdCity = 43,
                            CityCode = "TP43",
                            NameCity = "Ninh Thuận"
                        },
                        new
                        {
                            IdCity = 44,
                            CityCode = "TP44",
                            NameCity = "Phú Thọ"
                        },
                        new
                        {
                            IdCity = 45,
                            CityCode = "TP45",
                            NameCity = "Phú Yên"
                        },
                        new
                        {
                            IdCity = 46,
                            CityCode = "TP46",
                            NameCity = "Quảng Bình"
                        },
                        new
                        {
                            IdCity = 47,
                            CityCode = "TP47",
                            NameCity = "Quảng Nam"
                        },
                        new
                        {
                            IdCity = 48,
                            CityCode = "TP48",
                            NameCity = "Quảng Ngãi"
                        },
                        new
                        {
                            IdCity = 49,
                            CityCode = "TP49",
                            NameCity = "Quảng Ninh"
                        },
                        new
                        {
                            IdCity = 50,
                            CityCode = "TP50",
                            NameCity = "Quảng Trị"
                        },
                        new
                        {
                            IdCity = 51,
                            CityCode = "TP51",
                            NameCity = "Sóc Trăng"
                        },
                        new
                        {
                            IdCity = 52,
                            CityCode = "TP52",
                            NameCity = "Sơn La"
                        },
                        new
                        {
                            IdCity = 53,
                            CityCode = "TP53",
                            NameCity = "Tây Ninh"
                        },
                        new
                        {
                            IdCity = 54,
                            CityCode = "TP54",
                            NameCity = "Thái Bình"
                        },
                        new
                        {
                            IdCity = 55,
                            CityCode = "TP55",
                            NameCity = "Thái Nguyên"
                        },
                        new
                        {
                            IdCity = 56,
                            CityCode = "TP56",
                            NameCity = "Thanh Hóa"
                        },
                        new
                        {
                            IdCity = 57,
                            CityCode = "TP57",
                            NameCity = "Thừa Thiên Huế"
                        },
                        new
                        {
                            IdCity = 58,
                            CityCode = "TP58",
                            NameCity = "Tiền Giang"
                        },
                        new
                        {
                            IdCity = 59,
                            CityCode = "TP59",
                            NameCity = "Trà Vinh"
                        },
                        new
                        {
                            IdCity = 60,
                            CityCode = "TP60",
                            NameCity = "Tuyên Quang"
                        },
                        new
                        {
                            IdCity = 61,
                            CityCode = "TP61",
                            NameCity = "Vĩnh Long"
                        },
                        new
                        {
                            IdCity = 62,
                            CityCode = "TP62",
                            NameCity = "Vĩnh Phúc"
                        },
                        new
                        {
                            IdCity = 63,
                            CityCode = "TP63",
                            NameCity = "Yên Bái"
                        });
                });

            modelBuilder.Entity("TicketBus.Models.Coach", b =>
                {
                    b.Property<int>("IdCoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCoach"));

                    b.Property<string>("CoachCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Documents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBrand")
                        .HasColumnType("int");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPlate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("IdCoach");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdType");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("TicketBus.Models.District", b =>
                {
                    b.Property<int>("IdDistrict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDistrict"));

                    b.Property<string>("DistrictCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<string>("NameDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDistrict");

                    b.HasIndex("IdCity");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("TicketBus.Models.DropOff", b =>
                {
                    b.Property<int>("IdDropOff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDropOff"));

                    b.Property<string>("DropOffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBrand")
                        .HasColumnType("int");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<int?>("IdRoute")
                        .HasColumnType("int");

                    b.HasKey("IdDropOff");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdCity");

                    b.HasIndex("IdRoute");

                    b.ToTable("DropOffs");
                });

            modelBuilder.Entity("TicketBus.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdBrand")
                        .HasColumnType("int");

                    b.Property<string>("IdCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdPos")
                        .HasColumnType("int");

                    b.Property<string>("NameEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("IdEmployee");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdPos");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TicketBus.Models.Feedback", b =>
                {
                    b.Property<int>("IdFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFeedback"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdPassenger")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("IdFeedback");

                    b.HasIndex("IdPassenger");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("TicketBus.Models.News", b =>
                {
                    b.Property<int>("IdNews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNews"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdTypeNews")
                        .HasColumnType("int");

                    b.Property<string>("NewsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNews");

                    b.HasIndex("IdTypeNews");

                    b.ToTable("News");
                });

            modelBuilder.Entity("TicketBus.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TicketBus.Models.Passenger", b =>
                {
                    b.Property<int>("IdPassenger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPassenger"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePassenger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassengerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPassenger");

                    b.HasIndex("UserId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("TicketBus.Models.Pickup", b =>
                {
                    b.Property<int>("IdPickup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPickup"));

                    b.Property<int>("IdBrand")
                        .HasColumnType("int");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<int?>("IdRoute")
                        .HasColumnType("int");

                    b.Property<string>("PickupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPickup");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdCity");

                    b.HasIndex("IdRoute");

                    b.ToTable("Pickups");
                });

            modelBuilder.Entity("TicketBus.Models.Position", b =>
                {
                    b.Property<int>("IdPos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPos"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NamePos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("IdPos");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("TicketBus.Models.Price", b =>
                {
                    b.Property<int>("IdPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrice"));

                    b.Property<int?>("IdCoach")
                        .HasColumnType("int");

                    b.Property<int?>("IdRoute")
                        .HasColumnType("int");

                    b.Property<int>("IdSchedule")
                        .HasColumnType("int");

                    b.Property<int>("IdStopEnd")
                        .HasColumnType("int");

                    b.Property<int>("IdStopStart")
                        .HasColumnType("int");

                    b.Property<string>("PriceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPrice");

                    b.HasIndex("IdCoach");

                    b.HasIndex("IdRoute");

                    b.HasIndex("IdSchedule");

                    b.HasIndex("IdStopEnd");

                    b.HasIndex("IdStopStart");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("TicketBus.Models.RegistForm", b =>
                {
                    b.Property<int>("IdRegist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegist"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdBrand")
                        .HasColumnType("int");

                    b.Property<string>("RegistCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("IdRegist");

                    b.HasIndex("IdBrand")
                        .IsUnique()
                        .HasFilter("[IdBrand] IS NOT NULL");

                    b.ToTable("RegistForms");
                });

            modelBuilder.Entity("TicketBus.Models.RouteStop", b =>
                {
                    b.Property<int>("IdStop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStop"));

                    b.Property<int>("IdCity")
                        .HasColumnType("int");

                    b.Property<int>("IdRoute")
                        .HasColumnType("int");

                    b.Property<string>("StopCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.HasKey("IdStop");

                    b.HasIndex("IdCity");

                    b.HasIndex("IdRoute");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("TicketBus.Models.ScheduleDetails", b =>
                {
                    b.Property<int>("IdSchedule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSchedule"));

                    b.Property<TimeSpan>("ArriveTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DepartTime")
                        .HasColumnType("time");

                    b.Property<int>("IdCoach")
                        .HasColumnType("int");

                    b.Property<int>("IdRoute")
                        .HasColumnType("int");

                    b.HasKey("IdSchedule");

                    b.HasIndex("IdCoach");

                    b.HasIndex("IdRoute");

                    b.ToTable("ScheduleDetails");
                });

            modelBuilder.Entity("TicketBus.Models.Seat", b =>
                {
                    b.Property<int>("IdSeat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeat"));

                    b.Property<int?>("CoachIdCoach")
                        .HasColumnType("int");

                    b.Property<int>("IdCoach")
                        .HasColumnType("int");

                    b.Property<string>("SeatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("IdSeat");

                    b.HasIndex("CoachIdCoach");

                    b.HasIndex("IdCoach");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("TicketBus.Models.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicket"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdBill")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdPrice")
                        .HasColumnType("int");

                    b.Property<int?>("IdSeat")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TicketCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTicket");

                    b.HasIndex("IdBill");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("IdPrice");

                    b.HasIndex("IdSeat");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketBus.Models.TypeNews", b =>
                {
                    b.Property<int>("IdTypeNews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypeNews"));

                    b.Property<string>("NameTypeNews")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTypeNews");

                    b.ToTable("TypeNews");
                });

            modelBuilder.Entity("TicketBus.Models.VehicleType", b =>
                {
                    b.Property<int>("IdType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdType"));

                    b.Property<string>("NameType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdType");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            IdType = 1,
                            NameType = "Giường nằm CLC 34 chỗ",
                            SeatCount = 34,
                            State = 0,
                            TypeCode = "VT001"
                        },
                        new
                        {
                            IdType = 2,
                            NameType = "Giường nằm CLC 40 chỗ",
                            SeatCount = 40,
                            State = 0,
                            TypeCode = "VT002"
                        },
                        new
                        {
                            IdType = 3,
                            NameType = "Giường nằm CLC VIP 20 chỗ",
                            SeatCount = 20,
                            State = 0,
                            TypeCode = "VT003"
                        },
                        new
                        {
                            IdType = 4,
                            NameType = "Giường nằm massage 34 chỗ",
                            SeatCount = 34,
                            State = 0,
                            TypeCode = "VT004"
                        },
                        new
                        {
                            IdType = 5,
                            NameType = "Giường nằm massage 40 chỗ",
                            SeatCount = 40,
                            State = 0,
                            TypeCode = "VT005"
                        },
                        new
                        {
                            IdType = 6,
                            NameType = "Giường nằm đôi VIP 22 chỗ",
                            SeatCount = 22,
                            State = 0,
                            TypeCode = "VT006"
                        },
                        new
                        {
                            IdType = 7,
                            NameType = "Ghé Nằm CLC 34 chỗ",
                            SeatCount = 34,
                            State = 0,
                            TypeCode = "VT007"
                        },
                        new
                        {
                            IdType = 8,
                            NameType = "Ghé Nằm CLC 40 chỗ",
                            SeatCount = 40,
                            State = 0,
                            TypeCode = "VT008"
                        },
                        new
                        {
                            IdType = 9,
                            NameType = "Ghé Nằm VIP 20 chỗ",
                            SeatCount = 20,
                            State = 0,
                            TypeCode = "VT009"
                        },
                        new
                        {
                            IdType = 10,
                            NameType = "Ghé Nằm massage 34 chỗ",
                            SeatCount = 34,
                            State = 0,
                            TypeCode = "VT010"
                        },
                        new
                        {
                            IdType = 11,
                            NameType = "Ghế ngồi CLC 45 chỗ",
                            SeatCount = 45,
                            State = 0,
                            TypeCode = "VT011"
                        },
                        new
                        {
                            IdType = 12,
                            NameType = "Ghế ngồi CLC 50 chỗ",
                            SeatCount = 50,
                            State = 0,
                            TypeCode = "VT012"
                        },
                        new
                        {
                            IdType = 13,
                            NameType = "Ghế ngồi VIP 32 chỗ",
                            SeatCount = 32,
                            State = 0,
                            TypeCode = "VT013"
                        },
                        new
                        {
                            IdType = 14,
                            NameType = "Ghế ngồi Limousine 28 chỗ",
                            SeatCount = 28,
                            State = 0,
                            TypeCode = "VT014"
                        },
                        new
                        {
                            IdType = 15,
                            NameType = "Limousine DCar VIP 9 chỗ",
                            SeatCount = 9,
                            State = 0,
                            TypeCode = "VT015"
                        },
                        new
                        {
                            IdType = 16,
                            NameType = "Limousine President 11 chỗ",
                            SeatCount = 11,
                            State = 0,
                            TypeCode = "VT016"
                        },
                        new
                        {
                            IdType = 17,
                            NameType = "Limousine Fuso Rosa 17 chỗ",
                            SeatCount = 17,
                            State = 0,
                            TypeCode = "VT017"
                        },
                        new
                        {
                            IdType = 18,
                            NameType = "Limousine Skybus 19 chỗ",
                            SeatCount = 19,
                            State = 0,
                            TypeCode = "VT018"
                        },
                        new
                        {
                            IdType = 19,
                            NameType = "Limousine Jet VIP 22 chỗ",
                            SeatCount = 22,
                            State = 0,
                            TypeCode = "VT019"
                        },
                        new
                        {
                            IdType = 20,
                            NameType = "Limousine Auto Kingdom 26 chỗ",
                            SeatCount = 26,
                            State = 0,
                            TypeCode = "VT020"
                        },
                        new
                        {
                            IdType = 21,
                            NameType = "Xe khách giường nằm 34 chỗ",
                            SeatCount = 34,
                            State = 0,
                            TypeCode = "VT021"
                        },
                        new
                        {
                            IdType = 22,
                            NameType = "Xe khách giường nằm 40 chỗ",
                            SeatCount = 40,
                            State = 0,
                            TypeCode = "VT022"
                        },
                        new
                        {
                            IdType = 23,
                            NameType = "Xe khách giường đôi 20 chỗ",
                            SeatCount = 20,
                            State = 0,
                            TypeCode = "VT023"
                        },
                        new
                        {
                            IdType = 24,
                            NameType = "Xe khách giường đôi 34 chỗ",
                            SeatCount = 34,
                            State = 0,
                            TypeCode = "VT024"
                        },
                        new
                        {
                            IdType = 25,
                            NameType = "Xe ghế ngồi 12 chỗ Transit",
                            SeatCount = 12,
                            State = 0,
                            TypeCode = "VT025"
                        },
                        new
                        {
                            IdType = 26,
                            NameType = "Xe ghế ngồi 29 chỗ County",
                            SeatCount = 29,
                            State = 0,
                            TypeCode = "VT026"
                        },
                        new
                        {
                            IdType = 27,
                            NameType = "Xe ghế ngồi 34 chỗ Thaco Garden",
                            SeatCount = 34,
                            State = 1,
                            TypeCode = "VT027"
                        },
                        new
                        {
                            IdType = 28,
                            NameType = "Xe ghế ngồi 50 chỗ Giáp Bát Express",
                            SeatCount = 50,
                            State = 1,
                            TypeCode = "VT028"
                        },
                        new
                        {
                            IdType = 29,
                            NameType = "Xe giường nằm massage 38 chỗ",
                            SeatCount = 38,
                            State = 0,
                            TypeCode = "VT029"
                        },
                        new
                        {
                            IdType = 30,
                            NameType = "Xe giường nằm CLC 32 chỗ",
                            SeatCount = 32,
                            State = 0,
                            TypeCode = "VT030"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TicketBus.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TicketBus.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketBus.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TicketBus.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketBus.Models.Bill", b =>
                {
                    b.HasOne("TicketBus.Models.Passenger", "Passenger")
                        .WithMany("Bills")
                        .HasForeignKey("IdPassenger")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("TicketBus.Models.Brand", b =>
                {
                    b.HasOne("TicketBus.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TicketBus.Models.BusRoute", b =>
                {
                    b.HasOne("TicketBus.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketBus.Models.City", "EndCity")
                        .WithMany("EndRoutes")
                        .HasForeignKey("IdEndCity")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBus.Models.RegistForm", "RegistForm")
                        .WithMany()
                        .HasForeignKey("IdRegist");

                    b.HasOne("TicketBus.Models.City", "StartCity")
                        .WithMany("StartRoutes")
                        .HasForeignKey("IdStartCity")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Brand");

                    b.Navigation("EndCity");

                    b.Navigation("RegistForm");

                    b.Navigation("StartCity");
                });

            modelBuilder.Entity("TicketBus.Models.Coach", b =>
                {
                    b.HasOne("TicketBus.Models.Brand", "Brand")
                        .WithMany("Coaches")
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketBus.Models.VehicleType", "VehicleType")
                        .WithMany("Coaches")
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("TicketBus.Models.District", b =>
                {
                    b.HasOne("TicketBus.Models.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("City");
                });

            modelBuilder.Entity("TicketBus.Models.DropOff", b =>
                {
                    b.HasOne("TicketBus.Models.Brand", "Brand")
                        .WithMany("DropOffs")
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketBus.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBus.Models.BusRoute", "BusRoute")
                        .WithMany("DropOffs")
                        .HasForeignKey("IdRoute")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Brand");

                    b.Navigation("BusRoute");

                    b.Navigation("City");
                });

            modelBuilder.Entity("TicketBus.Models.Employee", b =>
                {
                    b.HasOne("TicketBus.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBus.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("IdPos")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Brand");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TicketBus.Models.Feedback", b =>
                {
                    b.HasOne("TicketBus.Models.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("IdPassenger")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("TicketBus.Models.News", b =>
                {
                    b.HasOne("TicketBus.Models.TypeNews", "TypeNews")
                        .WithMany()
                        .HasForeignKey("IdTypeNews")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TypeNews");
                });

            modelBuilder.Entity("TicketBus.Models.Notification", b =>
                {
                    b.HasOne("TicketBus.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketBus.Models.Passenger", b =>
                {
                    b.HasOne("TicketBus.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TicketBus.Models.Pickup", b =>
                {
                    b.HasOne("TicketBus.Models.Brand", "Brand")
                        .WithMany("Pickups")
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketBus.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBus.Models.BusRoute", "BusRoute")
                        .WithMany("Pickups")
                        .HasForeignKey("IdRoute")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Brand");

                    b.Navigation("BusRoute");

                    b.Navigation("City");
                });

            modelBuilder.Entity("TicketBus.Models.Price", b =>
                {
                    b.HasOne("TicketBus.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("IdCoach")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBus.Models.BusRoute", "BusRoute")
                        .WithMany()
                        .HasForeignKey("IdRoute")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBus.Models.ScheduleDetails", "ScheduleDetails")
                        .WithMany("Prices")
                        .HasForeignKey("IdSchedule")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketBus.Models.RouteStop", "RouteStopEnd")
                        .WithMany()
                        .HasForeignKey("IdStopEnd")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketBus.Models.RouteStop", "RouteStopStart")
                        .WithMany()
                        .HasForeignKey("IdStopStart")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("Coach");

                    b.Navigation("RouteStopEnd");

                    b.Navigation("RouteStopStart");

                    b.Navigation("ScheduleDetails");
                });

            modelBuilder.Entity("TicketBus.Models.RegistForm", b =>
                {
                    b.HasOne("TicketBus.Models.Brand", "Brand")
                        .WithOne("RegistForm")
                        .HasForeignKey("TicketBus.Models.RegistForm", "IdBrand")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("TicketBus.Models.RouteStop", b =>
                {
                    b.HasOne("TicketBus.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketBus.Models.BusRoute", "BusRoute")
                        .WithMany("RouteStops")
                        .HasForeignKey("IdRoute")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("City");
                });

            modelBuilder.Entity("TicketBus.Models.ScheduleDetails", b =>
                {
                    b.HasOne("TicketBus.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("IdCoach")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketBus.Models.BusRoute", "BusRoute")
                        .WithMany()
                        .HasForeignKey("IdRoute")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("TicketBus.Models.Seat", b =>
                {
                    b.HasOne("TicketBus.Models.Coach", null)
                        .WithMany("Seats")
                        .HasForeignKey("CoachIdCoach");

                    b.HasOne("TicketBus.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("IdCoach")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("TicketBus.Models.Ticket", b =>
                {
                    b.HasOne("TicketBus.Models.Bill", "Bill")
                        .WithMany("Tickets")
                        .HasForeignKey("IdBill")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBus.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBus.Models.Price", "Price")
                        .WithMany()
                        .HasForeignKey("IdPrice")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TicketBus.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("IdSeat")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Bill");

                    b.Navigation("Employee");

                    b.Navigation("Price");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("TicketBus.Models.Bill", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketBus.Models.Brand", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("DropOffs");

                    b.Navigation("Pickups");

                    b.Navigation("RegistForm");
                });

            modelBuilder.Entity("TicketBus.Models.BusRoute", b =>
                {
                    b.Navigation("DropOffs");

                    b.Navigation("Pickups");

                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("TicketBus.Models.City", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("EndRoutes");

                    b.Navigation("StartRoutes");
                });

            modelBuilder.Entity("TicketBus.Models.Coach", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketBus.Models.Passenger", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("TicketBus.Models.ScheduleDetails", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("TicketBus.Models.VehicleType", b =>
                {
                    b.Navigation("Coaches");
                });
#pragma warning restore 612, 618
        }
    }
}
